import { Component, OnInit, OnDestroy, inject, signal, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import {
  KafkaEventsService,
  PingEventPayload,
  PingPublishResponse,
  PingConsumerResponse,
  ConsumerGroupStatus,
  EventActivityLog
} from '../../services/kafka-events.service';

function generateShortId(length = 5): string {
  const chars = '0123456789ABCDEFGHJKLMNPQRSTUVWXYZ';
  let result = '';
  for (let i = 0; i < length; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return result;
}

@Component({
  selector: 'app-events-dashboard',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule, MatSnackBarModule],
  templateUrl: './events-dashboard.html',
  styleUrl: './events-dashboard.scss',
})
export class EventsDashboard implements OnInit, OnDestroy {
  private readonly eventsService = inject(KafkaEventsService);
  private readonly snackBar = inject(MatSnackBar);

  // Event Model Form State (auto-generated by default with 0-5 char eventId)
  eventId = signal<string>(generateShortId(5));
  eventMessage = signal<string>(crypto.randomUUID());
  eventSourceService = signal<string>('service-' + crypto.randomUUID().substring(0, 8));
  eventTimestamp = signal<number>(Date.now());
  autoGenerateOnSend = signal(true);

  // Batch sending configuration (for testing manual offset commit & service crashes)
  batchCount = signal<number>(5);
  batchDelaySec = signal<number>(3);
  isBatchRunning = signal<boolean>(false);
  batchProgress = signal<{ current: number; total: number; countdown: number } | null>(null);
  private batchTimeoutId: any = null;
  private countdownIntervalId: any = null;
  private isBatchCancelled = false;

  // Backward compatibility getter
  get messageText() {
    return this.eventMessage;
  }

  // Computed JSON payload
  currentPayload = computed<PingEventPayload>(() => ({
    id: this.eventId().trim(),
    message: this.eventMessage().trim(),
    sourceService: this.eventSourceService().trim(),
    timestamp: Number(this.eventTimestamp()) || Date.now(),
  }));

  currentPayloadJson = computed(() => {
    return JSON.stringify(this.currentPayload(), null, 2);
  });

  // Async States
  isSending = signal(false);
  isPolling = signal(false);
  autoPollEnabled = signal(false);
  autoPollTimer: any = null;

  // Active Tab: 'tester' | 'guide'
  activeTab = signal<'tester' | 'guide'>('tester');

  // Payload data
  lastPublished = signal<PingPublishResponse | null>(null);
  lastConsumed = signal<PingConsumerResponse | null>(null);
  lastPollTime = signal<Date | null>(null);
  consumerGroups = signal<ConsumerGroupStatus[]>([]);

  // Counters & Logs
  publishedCount = signal(0);
  consumedCount = signal(0);
  logs = signal<EventActivityLog[]>([]);

  // Computed Sync Status
  syncStatus = computed(() => {
    const pub = this.lastPublished();
    const con = this.lastConsumed();

    if (!pub) {
      return { state: 'IDLE', label: 'Idle / Ready', tone: 'neutral' };
    }
    if (con && con.id && con.id === pub.id) {
      return { state: 'SYNCED', label: 'End-to-End Verified: In Sync', tone: 'success' };
    }
    if (con && con.id && con.id !== pub.id) {
      return { state: 'LAG', label: 'Consumer at previous event', tone: 'warning' };
    }
    return { state: 'PENDING', label: 'Waiting for consumer to poll/receive', tone: 'accent' };
  });

  ngOnInit(): void {
    // Check initial state of consumer
    this.pollConsumer(false);
  }

  ngOnDestroy(): void {
    this.stopAutoPoll();
    this.cleanupBatch();
  }

  generateNewId(): void {
    this.eventId.set(generateShortId(5));
  }

  generateNewMessage(): void {
    this.eventMessage.set(crypto.randomUUID());
  }

  generateNewService(): void {
    const services = [
      'service',
      'demo-assets-service',
      'demo-planogram-service',
      'payment-gateway',
      'order-service',
      'inventory-service',
      'auth-service',
      'notification-service'
    ];
    const picked = services[Math.floor(Math.random() * services.length)];
    this.eventSourceService.set(`${picked}-${crypto.randomUUID().substring(0, 8)}`);
  }

  setTimestampToNow(): void {
    this.eventTimestamp.set(Date.now());
  }

  generateAll(showToast = true): void {
    this.generateNewId();
    this.generateNewMessage();
    this.generateNewService();
    this.setTimestampToNow();
    if (showToast) {
      this.snackBar.open('Generated fresh ID, message, and service for all fields', 'OK', { duration: 2000 });
    }
  }

  loadSamplePing(): void {
    this.eventId.set('EV001');
    this.eventMessage.set('Health check ping');
    this.eventSourceService.set('payment-gateway');
    this.eventTimestamp.set(1789668181521);
    this.snackBar.open('Reset to sample ping event', 'OK', { duration: 2000 });
  }

  publishPing(): void {
    const payload = this.currentPayload();
    if (!payload.message) {
      this.snackBar.open('Please enter a message payload', 'Dismiss', { duration: 3000 });
      return;
    }

    this.isSending.set(true);
    console.log('Sending ping event payload to API:', payload);

    this.eventsService.sendPing(payload).subscribe({
      next: (res) => {
        this.isSending.set(false);
        this.lastPublished.set(res);
        this.publishedCount.update((c) => c + 1);

        this.addLog({
          id: res.id,
          direction: 'PUBLISHED',
          sourceService: res.sourceService || payload.sourceService,
          message: res.message,
          timestamp: new Date(),
          status: 'SUCCESS',
          note: 'Sent to Kafka topic demo-ping-topic'
        });

        const pubDisplayId = res.id.length <= 8 ? res.id : `${res.id.substring(0, 8)}...`;
        this.snackBar.open(`Published Event: ${pubDisplayId}`, 'OK', { duration: 2500 });

        if (this.autoGenerateOnSend()) {
          this.generateAll(false);
        }

        if (!this.autoPollEnabled()) {
          setTimeout(() => this.pollConsumer(false), 800);
        }
      },
      error: (err) => {
        this.isSending.set(false);
        const errMsg = err?.error?.message || err?.message || 'Failed to publish to Kafka broker';
        this.snackBar.open(`Publish error: ${errMsg}`, 'Dismiss', { duration: 5000 });

        this.addLog({
          id: payload.id || 'error-' + Date.now(),
          direction: 'PUBLISHED',
          sourceService: payload.sourceService,
          message: payload.message,
          timestamp: new Date(),
          status: 'ERROR',
          note: errMsg
        });
      }
    });
  }

  startBatch(): void {
    if (this.isSending() || this.isBatchRunning()) return;

    const count = this.batchCount();
    const delaySec = this.batchDelaySec();
    const delayMs = delaySec * 1000;

    this.isBatchRunning.set(true);
    this.isBatchCancelled = false;
    let sent = 0;

    const baseMsg = this.eventMessage().trim() || crypto.randomUUID();
    const source = this.eventSourceService().trim() || ('service-' + crypto.randomUUID().substring(0, 8));

    const sendStep = (i: number) => {
      if (this.isBatchCancelled) {
        this.cleanupBatch();
        return;
      }

      this.batchProgress.set({
        current: i + 1,
        total: count,
        countdown: 0
      });

      const payload: PingEventPayload = {
        id: generateShortId(5),
        message: `${baseMsg} [Batch ${i + 1}/${count}]`,
        sourceService: source,
        timestamp: Date.now(),
      };

      this.isSending.set(true);
      this.eventsService.sendPing(payload).subscribe({
        next: (res) => {
          this.isSending.set(false);
          if (this.isBatchCancelled) {
            this.cleanupBatch();
            return;
          }

          sent++;
          this.lastPublished.set(res);
          this.publishedCount.update((c) => c + 1);

          this.addLog({
            id: res.id,
            direction: 'PUBLISHED',
            sourceService: res.sourceService || source,
            message: res.message,
            timestamp: new Date(),
            status: 'SUCCESS',
            note: `Batch ${sent}/${count} (delay: ${delaySec}s)`
          });

          // Check if there are more events in the batch
          if (i + 1 < count) {
            let remainingSec = delaySec;
            this.batchProgress.set({
              current: i + 1,
              total: count,
              countdown: remainingSec
            });

            this.countdownIntervalId = setInterval(() => {
              remainingSec--;
              if (remainingSec > 0 && !this.isBatchCancelled) {
                this.batchProgress.update((p) => p ? { ...p, countdown: remainingSec } : null);
              } else {
                clearInterval(this.countdownIntervalId);
                this.countdownIntervalId = null;
              }
            }, 1000);

            this.batchTimeoutId = setTimeout(() => {
              if (this.countdownIntervalId) {
                clearInterval(this.countdownIntervalId);
                this.countdownIntervalId = null;
              }
              sendStep(i + 1);
            }, delayMs);
          } else {
            // Completed all
            this.cleanupBatch();
            this.snackBar.open(`Completed batch of ${count} events with ${delaySec}s delay!`, 'OK', { duration: 3500 });
            if (!this.autoPollEnabled()) {
              setTimeout(() => this.pollConsumer(false), 800);
            }
          }
        },
        error: (err) => {
          this.isSending.set(false);
          this.cleanupBatch();
          const errMsg = err?.error?.message || err?.message || 'Batch request failed';
          this.snackBar.open(`Batch stopped at #${i + 1}: ${errMsg}`, 'Dismiss', { duration: 4000 });
        }
      });
    };

    sendStep(0);
  }

  stopBatch(): void {
    this.isBatchCancelled = true;
    this.cleanupBatch();
    this.snackBar.open('Batch sending stopped by user', 'Dismiss', { duration: 2500 });
  }

  private cleanupBatch(): void {
    this.isBatchRunning.set(false);
    this.isSending.set(false);
    this.batchProgress.set(null);
    if (this.batchTimeoutId) {
      clearTimeout(this.batchTimeoutId);
      this.batchTimeoutId = null;
    }
    if (this.countdownIntervalId) {
      clearInterval(this.countdownIntervalId);
      this.countdownIntervalId = null;
    }
  }

  publishBatch(count: number = this.batchCount()): void {
    this.batchCount.set(count);
    this.startBatch();
  }

  pollConsumer(showNotification = true): void {
    this.isPolling.set(true);
    this.eventsService.getLastReceivedPing().subscribe({
      next: (res) => {
        this.isPolling.set(false);
        this.lastPollTime.set(new Date());

        const hasPayload = res && res.id;
        const prevId = this.lastConsumed()?.id;

        if (hasPayload) {
          this.lastConsumed.set(res);
          if (res.id !== prevId) {
            this.consumedCount.update((c) => c + 1);
            this.addLog({
              id: res.id!,
              direction: 'CONSUMED',
              sourceService: res.sourceService || 'demo-planogram-service',
              message: res.message || '',
              timestamp: new Date(),
              status: 'SUCCESS',
              note: 'Received by planogram-service-group'
            });
          }

          if (showNotification) {
            const conDisplayId = res.id!.length <= 8 ? res.id! : `${res.id!.substring(0, 8)}...`;
            this.snackBar.open(`Latest consumed ID: ${conDisplayId}`, 'OK', { duration: 2000 });
          }
        } else {
          if (showNotification) {
            this.snackBar.open(res?.message || 'No ping received yet by consumer', 'OK', { duration: 2500 });
          }
        }
      },
      error: (err) => {
        this.isPolling.set(false);
        if (showNotification) {
          this.snackBar.open(`Consumer poll error: ${err.message}`, 'Dismiss', { duration: 4000 });
        }
      }
    });

    // Also fetch all 3 consumer group statuses
    this.eventsService.getConsumerGroups().subscribe({
      next: (groupsRes) => {
        if (groupsRes && groupsRes.groups) {
          this.consumerGroups.set(groupsRes.groups);
        }
      },
      error: () => {
        // Silently keep previous group states if endpoint not reachable yet
      }
    });
  }

  toggleAutoPoll(): void {
    if (this.autoPollEnabled()) {
      this.stopAutoPoll();
    } else {
      this.startAutoPoll();
    }
  }

  private startAutoPoll(): void {
    this.autoPollEnabled.set(true);
    this.pollConsumer(false);
    this.autoPollTimer = setInterval(() => {
      this.pollConsumer(false);
    }, 3000);
    this.snackBar.open('Auto-polling consumer every 3 seconds', 'OK', { duration: 2500 });
  }

  private stopAutoPoll(): void {
    this.autoPollEnabled.set(false);
    if (this.autoPollTimer) {
      clearInterval(this.autoPollTimer);
      this.autoPollTimer = null;
    }
  }

  clearLogs(): void {
    this.logs.set([]);
    this.snackBar.open('Event activity log cleared', 'OK', { duration: 2000 });
  }

  private addLog(entry: EventActivityLog): void {
    this.logs.update((current) => [entry, ...current.slice(0, 49)]);
  }

  formatTimestamp(val: any): string {
    if (!val) return '—';
    try {
      const num = Number(val);
      const date = !isNaN(num) && num > 10000000000 ? new Date(num) : new Date(val);
      if (isNaN(date.getTime())) return String(val);
      return date.toLocaleTimeString([], { hour12: false }) + '.' + String(date.getMilliseconds()).padStart(3, '0');
    } catch {
      return String(val);
    }
  }
}
